apiVersion: v1 # namespace for the application-related resources
kind: Namespace
metadata:
  name: application
  labels:
    name: application

---
apiVersion: apps/v1 # deployment - a set of application pods
kind: Deployment
metadata:
  name: record-store
  namespace: application
  labels:
    app: record-store
spec:
  replicas: 2 # number of pods to run
  selector:
    matchLabels:
      app: record-store
  template:
    metadata:
      labels:
        app: record-store
    spec:
      containers:
      - name: record-store
        image: acrrecordstore7pat.azurecr.io/record-store-app:1.0.0 # image from acr
        ports:
        - containerPort: 8080
        env:
        - name: ProxyTo
          value: http://127.0.0.1:5266 # proxy to the local service

---
apiVersion: v1 # the service to app internally accessible
kind: Service
metadata:
  name: record-store-svc
  namespace: application
spec:
  type: ClusterIP
  selector:
    app: record-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080