name: AKS deployments

on:  # Trigger this workflow manually
  workflow_dispatch:
    inputs:
      application:
        description: 'Application Workload'
        required: true
        default: 'record-store'

permissions:
  id-token: write
  contents: read

jobs:
  aks_deploy:
    name: Deploy to AKS
    runs-on: [self-hosted, linux] # Use a self-hosted, windows runner for this job
    steps:
      - name: "Checkout Application repository"
        uses: actions/checkout@main
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to AKS
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group rg-application-${{ inputs.application }} --name aks-${{ inputs.application }} --overwrite-existing
      - name: Deploy Record Store application
        run: |
          kubectl apply -f kubernetes_on_azure/manifests/application.yaml